# Generated by Django 3.1.1 on 2020-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetodo_app', '0002_auto_20200913_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
