# Generated by Django 3.1.1 on 2020-09-13 21:13

from django.db import migrations, models
import django.db.models.deletion
import model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('vetodo_app', '0003_auto_20200913_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TodoReminderNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetodo_app.todo')),
            ],
            bases=(models.Model, model_utils.DateTimeMixin),
        ),
    ]
